# Imagen base con Hadoop
FROM bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8

# Exponemos los puertos principales para NameNode WebUI y HDFS
EXPOSE 50070 9000

# Comando por defecto para acceder a bash
CMD ["bash"]